#!/usr/bin/env bash
# Starts a complete local Linvesther environment that needs no outside
# network: a local Postgres database, a local EVM chain with the registry
# contracts deployed, and an `.env.local` for the API and web app.
#
#   infra/local/up.sh            start (deploys the contracts the first time)
#   infra/local/up.sh --reset    forget the local chain and database first
#   infra/local/down.sh          stop the chain (its state is saved)
#
# Everything is local: the chain is a throwaway Anvil node and the database
# is `linvesther_local`, separate from any other database on the server.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
STATE_DIR="$ROOT/infra/local/.state"
RPC_URL="http://127.0.0.1:8545"
DB_NAME="linvesther_local"
# The compose file requires this for the worker service, which this script never
# starts, so any value will do here.
export BINANCE_WORKER_ENCRYPTION_KEY="${BINANCE_WORKER_ENCRYPTION_KEY:-unused-by-this-script}"
COMPOSE=(docker compose -f "$ROOT/infra/docker-compose.yml")
# Anvil's first account. Its key is public, printed by every Anvil install, and
# controls nothing outside this local chain.
LOCAL_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

for tool in docker forge anvil openssl curl python3; do
  command -v "$tool" >/dev/null || { echo "missing required tool: $tool" >&2; exit 1; }
done

mkdir -p "$STATE_DIR"

if [[ "${1:-}" == "--reset" ]]; then
  "$ROOT/infra/local/down.sh" || true
  rm -f "$STATE_DIR/anvil.json" "$ROOT/.env.local" "$ROOT/contracts/deployments/local.json"
  "${COMPOSE[@]}" up -d postgres
  until "${COMPOSE[@]}" exec -T postgres pg_isready -U linvestherzk >/dev/null 2>&1; do sleep 0.5; done
  "${COMPOSE[@]}" exec -T postgres psql -U linvestherzk -d postgres -c "DROP DATABASE IF EXISTS $DB_NAME" >/dev/null
fi

echo "==> database"
"${COMPOSE[@]}" up -d postgres
until "${COMPOSE[@]}" exec -T postgres pg_isready -U linvestherzk >/dev/null 2>&1; do sleep 0.5; done
if ! "${COMPOSE[@]}" exec -T postgres psql -U linvestherzk -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1; then
  "${COMPOSE[@]}" exec -T postgres psql -U linvestherzk -d postgres -c "CREATE DATABASE $DB_NAME" >/dev/null
fi

echo "==> local chain"
if ! curl -s -m 2 -X POST -H 'content-type: application/json' \
  --data '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' "$RPC_URL" >/dev/null 2>&1; then
  setsid nohup anvil --port 8545 --state "$STATE_DIR/anvil.json" --silent >"$STATE_DIR/anvil.log" 2>&1 &
  echo $! >"$STATE_DIR/anvil.pid"
  for _ in $(seq 1 100); do
    curl -s -m 2 -X POST -H 'content-type: application/json' \
      --data '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' "$RPC_URL" >/dev/null 2>&1 && break
    sleep 0.2
  done
fi

MANIFEST="$ROOT/contracts/deployments/local.json"
if [[ ! -f "$MANIFEST" || ! -f "$ROOT/.env.local" ]]; then
  echo "==> deploying the contracts"
  (
    cd "$ROOT/contracts"
    export DEPLOY_NETWORK_NAME=local
    forge script script/Deploy.s.sol --rpc-url "$RPC_URL" --private-key "$LOCAL_KEY" --broadcast >/dev/null
    forge script script/DeployProfile.s.sol --rpc-url "$RPC_URL" --private-key "$LOCAL_KEY" --broadcast >/dev/null
  )

  field() { python3 -c "import json,sys; print(json.load(open('$MANIFEST'))['$1'])"; }
  {
    echo "# Generated by infra/local/up.sh. Local only; never commit."
    echo "PORT=4301"
    echo "HOST=127.0.0.1"
    echo "SIWE_DOMAIN=localhost"
    echo "WEBAUTHN_RP_ID=localhost"
    echo "WEBAUTHN_ORIGIN=http://localhost:4300"
    echo "CORS_ORIGINS=http://localhost:4300"
    echo "DATABASE_URL=postgresql://linvestherzk:linvestherzk-local-dev-only@localhost:5433/$DB_NAME"
    echo "CHAIN_RPC_URL=$RPC_URL"
    echo "CHAIN_RELAYER_PRIVATE_KEY=$LOCAL_KEY"
    echo "IDENTITY_REGISTRY_ADDRESS=$(field identityRegistry)"
    echo "ACCOUNT_REGISTRY_ADDRESS=$(field accountRegistry)"
    echo "ACCOUNT_FACTORY_ADDRESS=$(field accountFactory)"
    echo "PROFILE_REGISTRY_ADDRESS=$(field profileRegistry)"
    echo "CHAIN_DEPLOY_BLOCK=$(field deployBlock)"
    echo "BINANCE_WORKER_ENCRYPTION_KEY=$(openssl rand -hex 32)"
    # This instance signs its own figures, so its proofs are self-attested
    # unless someone chooses to trust this key.
    echo "BINANCE_WORKER_A0_SIGNING_KEY=$(openssl rand -hex 32)"
    echo "BINANCE_WORKER_BINARY_PATH=$ROOT/services/target/debug/binance-worker"
  } >"$ROOT/.env.local"
  chmod 600 "$ROOT/.env.local"
fi

cat <<MSG

Ready. Start the API and the web app in two terminals:

  set -a; source .env.local; set +a; pnpm --filter @linvestherzk/api start
  pnpm --filter @linvestherzk/web dev

then open http://localhost:4300 . Build the worker once with:

  cargo build -p binance-worker --manifest-path services/Cargo.toml

Add --no-default-features to skip the zero-knowledge proving toolchain.
MSG
