// Copies the real ABIs Foundry compiled (contracts/out/*) into
// src/identity/abi.ts, run as an explicit build step — never edited by
// hand, so the indexer's event decoding can't silently drift from what
// the contracts actually emit. Requires `forge build` to have already
// produced contracts/out/.
import { writeFileSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const contractsOut = path.resolve(here, "../../../contracts/out");

interface ForgeArtifact {
  abi: unknown[];
}

function readAbi(contractFile: string, contractName: string): unknown[] {
  const artifactPath = path.join(contractsOut, `${contractFile}.sol`, `${contractName}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8")) as ForgeArtifact;
  return artifact.abi;
}

const identityRegistryAbi = readAbi("IdentityRegistry", "IdentityRegistry");
const accountRegistryAbi = readAbi("AccountRegistry", "AccountRegistry");
const accountFactoryAbi = readAbi("AccountFactory", "AccountFactory");
const webAuthnAccountAbi = readAbi("WebAuthnAccount", "WebAuthnAccount");
const p256VaultAccountAbi = readAbi("P256VaultAccount", "P256VaultAccount");

const profileRegistryAbi = readAbi("ProfileRegistry", "ProfileRegistry");

const output = `// Generated by scripts/exportAbi.ts from contracts/out/ — do not
// edit by hand. Re-run the script after any contract change instead.
import type { Abi } from "viem";

export const identityRegistryAbi = ${JSON.stringify(identityRegistryAbi, null, 2)} as const satisfies Abi;
export const accountRegistryAbi = ${JSON.stringify(accountRegistryAbi, null, 2)} as const satisfies Abi;
export const accountFactoryAbi = ${JSON.stringify(accountFactoryAbi, null, 2)} as const satisfies Abi;
export const webAuthnAccountAbi = ${JSON.stringify(webAuthnAccountAbi, null, 2)} as const satisfies Abi;
export const p256VaultAccountAbi = ${JSON.stringify(p256VaultAccountAbi, null, 2)} as const satisfies Abi;
export const profileRegistryAbi = ${JSON.stringify(profileRegistryAbi, null, 2)} as const satisfies Abi;
`;

writeFileSync(path.resolve(here, "../src/identity/abi.ts"), output);
console.log("wrote src/identity/abi.ts");
