[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^3.0.6", default-features = false, features = ['std'] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
k256 = { version = "0.13", features = ["ecdsa"] }
sha2 = "0.10"
